name: polyeme
version: 0.1.0.0
github: "mihnea-s/polyeme"
license: OtherLicense
author: "Mihnea Stoian"
maintainer: "mihn.stn@pm.me"
copyright: "2020 Mihnea Stoian"

extra-source-files:
  - README.md

synopsis: Interpreter for a scheme
category: Interpreter
description: Please see the README on GitHub at <https://github.com/mihnea-s/polyeme#readme>

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - haskeline
  - mtl
  - parsec
  - unordered-containers
  - process
  - vector

library:
  source-dirs: src

executables:
  polymer:
    main: Main.hs
    source-dirs: polymer
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - polyeme

tests:
  polymer-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - polyeme
